image: Ubuntu  # образ для сборки

stack:
  jdk 11  # версия JDK

services:
  - docker

branches:
  only:
    - master  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # - ?????
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов); права на запуск CI для Linux
  - java -jar artifacts/app-deadline.jar -P:jdbc.url=jdbc:mysql://localhost:3306/deadline -P:jdbc.user=app -P:jdbc.password=pass &
  # +x добавить права на (execute) выполнение файла (chmod (от англ. change mode) — команда для изменения прав доступа к файлам и каталогам, используемая в Unix-подобных операционных системах)
  - chmod +x gradlew

build_script:
  - ./docker-compose up --build
  # запускаем тест, флаг --info позволяет выводить больше информации, стартуем Selenide в Headless-режиме
  - ./gradlew test --info -Dselenide.headless=true